INSERT INTO planet  (id, name, rotation_period, orbital_period, diameter, climate, gravity, terrain, surface_water, population, created, edited)VALUES
  (1, 'Tatooine'),
  (2, 'Alderaan'),
  (3, 'Yavin IV'),
  (4, 'Hoth'),
  (5, 'Dagobah'),
  (6, 'Bespin'),
  (7, 'Endor'),
  (8, 'Naboo'),
  (9, 'Coruscant'),
  (10, 'Kamino'),
  (11, 'Geonosis'),
  (12, 'Utapau'),
  (13, 'Mustafar'),
  (14, 'Kashyyyk'),
  (15, 'Polis Massa'),
  (16, 'Mygeeto'),
  (17, 'Felucia'),
  (18, 'Cato Neimoidia'),
  (19, 'Saleucami'),
  (20, 'Stewjon'),
  (21, 'Eriadu'),
  (22, 'Corellia'),
  (23, 'Rodia'),
  (24, 'Nal Hutta'),
  (25, 'Dantooine'),
  (26, 'Bestine IV'),
  (27, 'Ord Mantell'),
  (29, 'Trandosha'),
  (30, 'Socorro'),
  (31, 'Mon Cala'),
  (32, 'Chandrila'),
  (33, 'Sullust'),
  (34, 'Toydaria'),
  (35, 'Malastare'),
  (36, 'Dathomir'),
  (37, 'Ryloth'),
  (38, 'Aleen Minor'),
  (39, 'Vulpter'),
  (40, 'Troiken'),
  (41, 'Tund'),
  (42, 'Haruun Kal'),
  (43, 'Cerea'),
  (44, 'Glee Anselm'),
  (45, 'Iridonia'),
  (46, 'Tholoth'),
  (47, 'Iktotch'),
  (48, 'Quermia'),
  (49, 'Dorin'),
  (50, 'Champala'),
  (51, 'Mirial'),
  (52, 'Serenno'),
  (53, 'Concord Dawn'),
  (54, 'Zolan'),
  (55, 'Ojom'),
  (56, 'Skako'),
  (57, 'Muunilinst'),
  (58, 'Shili'),
  (59, 'Kalee'),
  (60, 'Umbara'),
  (61, 'Jakku');

INSERT INTO person  (id, name, height, mass, hair_color, skin_color, eye_color, birth_year, gender, homeworld, created, edited)VALUES
  (1, 'Luke Skywalker'),
  (2, 'C-3PO'),
  (3, 'R2-D2'),
  (4, 'Darth Vader'),
  (5, 'Leia Organa'),
  (6, 'Owen Lars'),
  (7, 'Beru Whitesun lars'),
  (8, 'R5-D4'),
  (9, 'Biggs Darklighter'),
  (10, 'Obi-Wan Kenobi'),
  (11, 'Anakin Skywalker'),
  (12, 'Wilhuff Tarkin'),
  (13, 'Chewbacca'),
  (14, 'Han Solo'),
  (15, 'Greedo'),
  (16, 'Jabba Desilijic Tiure'),
  (18, 'Wedge Antilles'),
  (19, 'Jek Tono Porkins'),
  (20, 'Yoda'),
  (21, 'Palpatine'),
  (22, 'Boba Fett'),
  (23, 'IG-88'),
  (24, 'Bossk'),
  (25, 'Lando Calrissian'),
  (26, 'Lobot'),
  (27, 'Ackbar'),
  (28, 'Mon Mothma'),
  (29, 'Arvel Crynyd'),
  (30, 'Wicket Systri Warrick'),
  (31, 'Nien Nunb'),
  (32, 'Qui-Gon Jinn'),
  (33, 'Nute Gunray'),
  (34, 'Finis Valorum'),
  (35, 'Padmé Amidala'),
  (36, 'Jar Jar Binks'),
  (37, 'Roos Tarpals'),
  (38, 'Rugor Nass'),
  (39, 'Ric Olié'),
  (40, 'Watto'),
  (41, 'Sebulba'),
  (42, 'Quarsh Panaka'),
  (43, 'Shmi Skywalker'),
  (44, 'Darth Maul'),
  (45, 'Bib Fortuna'),
  (46, 'Ayla Secura'),
  (47, 'Ratts Tyerell'),
  (48, 'Dud Bolt'),
  (49, 'Gasgano'),
  (50, 'Ben Quadinaros'),
  (51, 'Mace Windu'),
  (52, 'Ki-Adi-Mundi'),
  (53, 'Kit Fisto'),
  (54, 'Eeth Koth'),
  (55, 'Adi Gallia'),
  (56, 'Saesee Tiin'),
  (57, 'Yarael Poof'),
  (58, 'Plo Koon'),
  (59, 'Mas Amedda'),
  (60, 'Gregar Typho'),
  (61, 'Cordé'),
  (62, 'Cliegg Lars'),
  (63, 'Poggle the Lesser'),
  (64, 'Luminara Unduli'),
  (65, 'Barriss Offee'),
  (66, 'Dormé'),
  (67, 'Dooku'),
  (68, 'Bail Prestor Organa'),
  (69, 'Jango Fett'),
  (70, 'Zam Wesell'),
  (71, 'Dexter Jettster'),
  (72, 'Lama Su'),
  (73, 'Taun We'),
  (74, 'Jocasta Nu'),
  (75, 'R4-P17'),
  (76, 'Wat Tambor'),
  (77, 'San Hill'),
  (78, 'Shaak Ti'),
  (79, 'Grievous'),
  (80, 'Tarfful'),
  (81, 'Raymus Antilles'),
  (82, 'Sly Moore'),
  (83, 'Tion Medon'),
  (84, 'Finn'),
  (85, 'Rey'),
  (86, 'Poe Dameron'),
  (87, 'BB8'),
  (88, 'Captain Phasma');

INSERT INTO species  (id, name, classification, designation, average_height, skin_colors, hair_colors, eye_colors, average_lifespan, homeworld, language, created, edited)VALUES
  (1, 'Human'),
  (2, 'Droid'),
  (3, 'Wookiee'),
  (4, 'Rodian'),
  (5, 'Hutt'),
  (6, 'Yoda''s species'),
  (7, 'Trandoshan'),
  (8, 'Mon Calamari'),
  (9, 'Ewok'),
  (10, 'Sullustan'),
  (11, 'Neimodian'),
  (12, 'Gungan'),
  (13, 'Toydarian'),
  (14, 'Dug'),
  (15, 'Twi''lek'),
  (16, 'Aleena'),
  (17, 'Vulptereen'),
  (18, 'Xexto'),
  (19, 'Toong'),
  (20, 'Cerean'),
  (21, 'Nautolan'),
  (22, 'Zabrak'),
  (23, 'Tholothian'),
  (24, 'Iktotchi'),
  (25, 'Quermian'),
  (26, 'Kel Dor'),
  (27, 'Chagrian'),
  (28, 'Geonosian'),
  (29, 'Mirialan'),
  (30, 'Clawdite'),
  (31, 'Besalisk'),
  (32, 'Kaminoan'),
  (33, 'Skakoan'),
  (34, 'Muun'),
  (35, 'Togruta'),
  (36, 'Kaleesh'),
  (37, 'Pau''an');

INSERT INTO vehicle  (id, name, model, manufacturer, cost_in_credits, length, max_atmosphering_speed, crew, passengers, cargo_capacity, consumables, vehicle_class, created, edited)VALUES
  (4, 'Sand Crawler'),
  (6, 'T-16 skyhopper'),
  (7, 'X-34 landspeeder'),
  (8, 'TIE/LN starfighter'),
  (14, 'Snowspeeder'),
  (16, 'TIE bomber'),
  (18, 'AT-AT'),
  (19, 'AT-ST'),
  (20, 'Storm IV Twin-Pod cloud car'),
  (24, 'Sail barge'),
  (25, 'Bantha-II cargo skiff'),
  (26, 'TIE/IN interceptor'),
  (30, 'Imperial Speeder Bike'),
  (33, 'Vulture Droid'),
  (34, 'Multi-Troop Transport'),
  (35, 'Armored Assault Tank'),
  (36, 'Single Trooper Aerial Platform'),
  (37, 'C-9979 landing craft'),
  (38, 'Tribubble bongo'),
  (42, 'Sith speeder'),
  (44, 'Zephyr-G swoop bike'),
  (45, 'Koro-2 Exodrive airspeeder'),
  (46, 'XJ-6 airspeeder'),
  (50, 'LAAT/i'),
  (51, 'LAAT/c'),
  (53, 'AT-TE'),
  (54, 'SPHA'),
  (55, 'Flitknot speeder'),
  (56, 'Neimoidian shuttle'),
  (57, 'Geonosian starfighter'),
  (60, 'Tsmeu-6 personal wheel bike'),
  (62, 'Emergency Firespeeder'),
  (67, 'Droid tri-fighter'),
  (69, 'Oevvaor jet catamaran'),
  (70, 'Raddaugh Gnasp fluttercraft'),
  (71, 'Clone turbo tank'),
  (72, 'Corporate Alliance tank droid'),
  (73, 'Droid gunship'),
  (76, 'AT-RT');

INSERT INTO starship  (id, name, model, manufacturer, cost_in_credits, length, max_atmosphering_speed, crew, passengers, cargo_capacity, consumables, hyperdrive_rating, mglt, starship_class, created)VALUES
  (2, 'CR90 corvette'),
  (3, 'Star Destroyer'),
  (5, 'Sentinel-class landing craft'),
  (9, 'Death Star'),
  (10, 'Millennium Falcon'),
  (11, 'Y-wing'),
  (12, 'X-wing'),
  (13, 'TIE Advanced x1'),
  (15, 'Executor'),
  (17, 'Rebel transport'),
  (21, 'Slave 1'),
  (22, 'Imperial shuttle'),
  (23, 'EF76 Nebulon-B escort frigate'),
  (27, 'Calamari Cruiser'),
  (28, 'A-wing'),
  (29, 'B-wing'),
  (31, 'Republic Cruiser'),
  (32, 'Droid control ship'),
  (39, 'Naboo fighter'),
  (40, 'Naboo Royal Starship'),
  (41, 'Scimitar'),
  (43, 'J-type diplomatic barge'),
  (47, 'AA-9 Coruscant freighter'),
  (48, 'Jedi starfighter'),
  (49, 'H-type Nubian yacht'),
  (52, 'Republic Assault ship'),
  (58, 'Solar Sailer'),
  (59, 'Trade Federation cruiser'),
  (61, 'Theta-class T-2c shuttle'),
  (63, 'Republic attack cruiser'),
  (64, 'Naboo star skiff'),
  (65, 'Jedi Interceptor'),
  (66, 'arc-170'),
  (68, 'Banking clan frigate'),
  (74, 'Belbullab-22 starfighter'),
  (75, 'V-wing'),
  (77, 'T-70 X-wing fighter');

INSERT INTO film  (id, title, episode_id, opening_crawl, director, producer, release_date, created, edited)VALUES
  (1, 'A New Hope'),
  (2, 'The Empire Strikes Back'),
  (3, 'Return of the Jedi'),
  (4, 'The Phantom Menace'),
  (5, 'Attack of the Clones'),
  (6, 'Revenge of the Sith'),
  (7, 'The Force Awakens');

